# Deploy to GitHub Pages
# Builds the site (dist) and publishes it. Also writes a CNAME file for the custom domain.

name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Change to your default branch if not 'main'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # NOTE: no "cache: npm" here, to avoid lockfile errors

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build (outputs to dist)
        run: npm run build

      - name: Write CNAME for custom domain (www)
        # Forces the deployed artifact to use www.logos-and-light.com
        run: |
          mkdir -p dist
          echo "www.logos-and-light.com" > dist/CNAME

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    name: Deploy to Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
